add dependency for enterprise permissions migration
Without this running `sqlmigrate` command fails with the following error:

    ValueError: The field enterprise.EnterprisePermissions.account was declared with a lazy reference to 'accounting.billingaccount', but app 'accounting' isn't installed