Dynamic transaction_exempt_databases
Resolves error in TestCase._enter_atomics:
AssertionError: Database queries to 'icds-ucr' are not allowed in this test. Add 'icds-ucr' to corehq.apps.accounting.tests.test_autopay.TestBillingAutoPay.databases to ensure proper test isolation and silence this failure.

(cherry picked from commit 135bf37bbe5e8efe4ca6084ba0d3f15716618871)