Allow docker tests to be run more than once
Previously it was not possible to run tests in docker (./scripts/docker test ...) more than once without completely destroying test containers and volumes because subsequent test runs invoke a db name check during setup, which does not allow databases with names that do not start with "test_". This check was previously violated by the "commcare_ucr_citus" db. It is unclear how the first test run avoids that check. Maybe that should be fixed?

Error seen on second and subsequent docker test runs:

ERROR: test suite for <corehq.tests.nose.HqdbContext object at 0x7fa191a3db38>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vendor/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/vendor/lib/python3.6/site-packages/nose/suite.py", line 297, in setUp
    self.setupContext(context)
  File "/vendor/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/vendor/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/mnt/commcare-hq/corehq/util/test_utils.py", line 415, in time_limit
    rval = func(*args, **kw)
  File "/mnt/commcare-hq/corehq/tests/nose.py", line 207, in setup
    if self.skip_setup_for_reuse_db and self._databases_ok():
  File "/mnt/commcare-hq/corehq/tests/nose.py", line 241, in _databases_ok
    assert db["NAME"].startswith(TEST_DATABASE_PREFIX), db["NAME"]
AssertionError: commcare_ucr_citus