Fix broken test
ProgrammingError: each UNION query must have the same number of columns
LINE 1: ...) AND "max_lens"."max_id" = ("cte"."id"))) SELECT "locations...

get_descendants (CTE) adds "_cte_exists" column. The annoying thing is that column does not even need to be in the select list, but Django doesn't provide a way to exclude it that I know of.