TypeError: can only concatenate list (not "str") to list
[ci skip]
I don't think this had ever been used.  I've got tests forthcoming, but there
was a bug in the test code that I want to PR separately.