Update urllib3 version for docs tests
urllib3>=1.26.13 causes an error in the docs tests:

Traceback (most recent call last):
  File ".../site-packages/sphinx/ext/autodoc/importer.py", line 60, in import_module
    return importlib.import_module(modname)
  ...
  File ".../corehq/__init__.py", line 43, in <module>
    assert _state._tls.current_app is None, "Current app already created"
AssertionError: Current app already created