Fix test_set_index_normal to account for settings deprecated in ES 2.x
Fixes for ES 2.x:
  pillowtop.tests.test_elasticsearch:ElasticPillowTest.test_set_index_normal

Fixes for ES 1.x:
  elasticsearch.exceptions.RequestError: TransportError(400, "ElasticsearchIllegalArgumentException[Can't update non dynamic settings[[index.max_result_window]] for open indices [[test_hqusers_2017-09-07]]]")