SQL objects are created in a transaction that is rolled back
This raised an error on Django 4.2:
ValueError: Event object can't be deleted because its event_id attribute is set to None.