Dynamic TestCase.databases
Resolves errors in ICDS tests:
AssertionError: Database queries to 'icds-ucr' are not allowed in this test. Add 'icds-ucr' to custom.icds.tests.test_aww_vhnd_survey.TestAWWVHNDSurveyIndicator.databases to ensure proper test isolation and silence this failure.

(cherry picked from commit 1b27492dfb4cf2d547354bb0852a0d628ee0f849)