Patch to prevent ignored error with retry in test
The sync_user_phone_numbers task catches Exception and retries 10 times, which caused a long cascade of ignored errors:

AssertionError: Database queries to 'default' are not allowed in SimpleTestCase subclasses.