Handle null doc_type in KafkaProcessor
Fixes error in AppPillowTest.test_hard_delete_app

TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

which was caused by

IntegrityError: null value in column "doc_type" of relation "cleanup_deletedcouchdoc" violates not-null constraint