Fix location fixture tests
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use include_only.set() instead.
(cherry picked from commit a115c677ea447f302ec1cd911b84e9c9ef9613ae)