Add test to ensure foreign key integrity in domain dump
Currently there are some SQL models included in the domain dump that
reference other models via a foreign key that are not included in the
domain dump. This leads to constraint violations when attempting to
load the dumped models.

Here is the output of this test at the time it was added:

AssertionError: Not all foreign key relationships will not be included in the domain dump.

data_interfaces.CaseRuleAction foreign keys to these uncovered models:
	data_interfaces.CaseDeduplicationActionDefinition

generic_inbound.ConfigurableAPI foreign keys to these uncovered models:
	userreports.UCRExpression

generic_inbound.ConfigurableApiValidation foreign keys to these uncovered models:
	userreports.UCRExpression

scheduling.AlertEvent foreign keys to these uncovered models:
	scheduling.SMSCallbackContent

scheduling.CasePropertyTimedEvent foreign keys to these uncovered models:
	scheduling.SMSCallbackContent

scheduling.RandomTimedEvent foreign keys to these uncovered models:
	scheduling.SMSCallbackContent

scheduling.TimedEvent foreign keys to these uncovered models:
	scheduling.SMSCallbackContent

users.RolePermission foreign keys to these uncovered models:
	users.Permission