Uninstall enum34
This is a holdover from long since passed Python 2.7 days. It probably should have been removed long ago. `enum34` is a backport of the stdlib enum module for Python versions < 3.4, so we no longer need it since we require 3.6.

Error seen attempting to `pip install psycogreen==1.0.2` when enum34 is installed:

AttributeError: module 'enum' has no attribute 'IntFlag'

Relevant links:
https://stackoverflow.com/q/43124775/10840
https://github.com/pypa/pip/issues/8214