Fix dump_domain_data --console
Previously gave the following error
if called with multiple dumpers (the default)
because the stdout stream was getting closed mid-write.

```
CommandError: Unable to serialize database: I/O operation on closed file.
```