Attempt to fix flaky test with decorator
Cause of failure is unclear. Also unclear if the @flaky_slow decorator will reduce the failure rate (grasping at a solution here). Details from Travis for future reference:

```
FAIL: corehq.apps.sms.tests.test_backends:OutgoingFrameworkTestCase.test_choosing_appropriate_backend_for_outgoing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/sms/tests/test_backends.py", line 932, in test_choosing_appropriate_backend_for_outgoing
    self.__test_global_backend_map()
  File "/mnt/commcare-hq-ro/corehq/apps/sms/tests/test_backends.py", line 762, in __test_global_backend_map
    self.assertTrue(send_sms(self.domain, None, '15551234567', 'Test for BACKEND2'))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
kafka_producer_audit: DEBUG: PRE-SEND,Domain,e588cbc4df9e1468ae54264a04156c74,d8ee4c0982e340fa92e6ebbad36fd8ff
kafka_producer_audit: DEBUG: SENT,Domain,e588cbc4df9e1468ae54264a04156c74,d8ee4c0982e340fa92e6ebbad36fd8ff
celery.app.trace: INFO: Task corehq.apps.accounting.tasks.restore_logos[005f5854-df49-4a5a-9e3c-dfd03c95df12] succeeded in 0.01238757600003737s: None
kafka_producer_audit: DEBUG: PRE-SEND,Domain,e588cbc4df9e1468ae54264a04156c74,8b1a4d919a2248d5a10382cf34c608dc
kafka_producer_audit: DEBUG: SENT,Domain,e588cbc4df9e1468ae54264a04156c74,8b1a4d919a2248d5a10382cf34c608dc
kafka_producer_audit: DEBUG: PRE-SEND,Domain,e588cbc4df9e1468ae54264a04156c74,30a3e10ef2a545e6962805c5208ffa9f
kafka_producer_audit: DEBUG: SENT,Domain,e588cbc4df9e1468ae54264a04156c74,30a3e10ef2a545e6962805c5208ffa9f
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'test-domain', '', None, '')
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'test-domain', '', None, None)
root: INFO: Received Form 338375203df44486879f9172260c245d with 0 attachments
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='redis-object-lock-XFormInstanceSQL-338375203df44486879f9172260c245d', timeout=900)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='redis-object-lock-CommCareCaseSQL-9619c5f7b1094a78ba0dc2b4e4940354', timeout=120)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='redis-object-lock-CommCareCaseSQL-9619c5f7b1094a78ba0dc2b4e4940354', timeout=120)
root: DEBUG: Saving new form: XFormInstance(form_id='338375203df44486879f9172260c245d', domain='test-domain', xmlns='http://commcarehq.org/case', )
kafka_producer_audit: DEBUG: PRE-SEND,XFormInstance,338375203df44486879f9172260c245d,4b3bdc87f72746fba29a933b94393988
kafka_producer_audit: DEBUG: SENT,XFormInstance,338375203df44486879f9172260c245d,4b3bdc87f72746fba29a933b94393988
kafka_producer_audit: DEBUG: PRE-SEND,CommCareCase,9619c5f7b1094a78ba0dc2b4e4940354,7119560f44cd4de3a529de6fa8e2a171
kafka_producer_audit: DEBUG: SENT,CommCareCase,9619c5f7b1094a78ba0dc2b4e4940354,7119560f44cd4de3a529de6fa8e2a171
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='sync-case-for-messaging-9619c5f7b1094a78ba0dc2b4e4940354', timeout=300)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='sync-contact-phone-numbers-for-9619c5f7b1094a78ba0dc2b4e4940354', timeout=300)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='reserve-phone-number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='reserve-phone-number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='sync-contact-phone-numbers-for-9619c5f7b1094a78ba0dc2b4e4940354', timeout=300)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='sync-case-for-messaging-9619c5f7b1094a78ba0dc2b4e4940354', timeout=300)
celery.app.trace: INFO: Task corehq.messaging.tasks.sync_case_for_messaging[9d2a1cff-9cc6-467e-8650-fe050f37ae0f] succeeded in 0.03447385599997688s: None
root: INFO: Finished normal processing for Form 338375203df44486879f9172260c245d
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='redis-object-lock-XFormInstanceSQL-338375203df44486879f9172260c245d', timeout=900)
notify: ERROR: Notify Exception: [SMS OUT] Error processing SMS
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/sms/api.py", line 298, in send_message_via_backend
    "  Please investigate why this function was called.") % msg.domain
Exception: Domain 'test-domain' does not have permission to send SMS.  Please investigate why this function was called.
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: acquire TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-by_owner_id-9619c5f7b1094a78ba0dc2b4e4940354', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_two_way_number-15551234567', timeout=60)
corehq.tests.noseplugins.redislocks: INFO: release TestLock(name='PhoneNumber-CacheAccessor-get_number_pending_verification-15551234567', timeout=60)
--------------------- >> end captured logging << ---------------------
```