Replace _.delay() with ko.pureComputed()
This fixes an error that occurs when `caseConfig.caseConfigViewModel` is
changed to an observable to allow form actions to be refreshed on ajax
success (that change will be made in a later commit).

This works because `ko.pureComputed` is lazier than `ko.computed`. It
defers execution long enough for `caseConfig.caseConfigViewModel.actionType`
to be created.

Full error when calling `self.caseConfigViewModel(caseConfigViewModel(self))`
on ajax success:

TypeError: Unable to process binding "if: function(){return actionType() ==='open' }"
Message: Unable to process binding "template: function(){return {
                        name:'case-config:case-transaction',data:case_transaction} }"
Message: Unable to process binding "template: function(){return { name:"case-config:case-transaction:case-properties"} }"
Message: Unable to process binding "foreach: function(){return visible_case_properties }"
Message: Unable to process binding "template: function(){return 'case-config:case-properties:question' }"
Message: Unable to process binding "questionsSelect: function(){return $root.getQuestions('all',false,case_transaction.allow.repeats(),true) }"
Message: can't access property "repeats", case_transaction.allow is undefined

The most important part is the last line.