Update Dockerfile for Python 3.13
Forces lxml to be built against the local libxml2-dev to resolve
xmlsec.InternalError: (-1, 'lxml & xmlsec libxml2 library version mismatch')

This can be revisited if lxml and xmlsec versions with pre-build wheels can be found.

`.*` was removed from .dockerignore to support `COPY .python-version ...`