Create + unregister non-abstract models for tests
Prevents other test failures:
- corehq.apps.domain.tests.test_deletion_models:test_deletion_sql_models
  AssertionError: Not all Django models are covered by domain deletion.
- corehq.sql_db.tests.test_model_partitioning:TestPartitionedModelsWithMultipleDBs.test_models_are_located_in_correct_dbs('scheduling', False)
  UndefinedTable: relation "scheduling_content" does not exist