Fix db router
corehq.apps.commtrack.tests.test_xml.CommTrackArchiveSubmissionTestSQL.test_archive_last_form was failing with

django.db.utils.IntegrityError: insert or update on table "form_processor_ledgervalue" violates foreign key constraint "cd40c15ceaad5d793e09d0b69eb4ed88"
DETAIL:  Key (case_id)=(...) is not present in table "form_processor_commcarecasesql".

(cherry picked from commit 29abc6bc359d6505667ad66b2c1bf75675286282)