Use canonical IANA timezone name in audit API test
django.db.utils.DataError: time zone "US/Eastern" not recognized

The postgres 18 container was built on debian-trixie, which no longer
includes legacy timezones in its database. The official postgres docker
container only supports the two latest versions of debian. While we
could pin our custom postgres build to the previous version (bookworm)
to avoid this issue for now, we will have to face it at some point so
I'm just updating this test.

My understanding is that it would be unreasonable to try to support legacy
timezone names, and therefore no followup action is needed on our part
to ensure legacy names can be saved in postgres. I am not aware of other
parts of our codebase that support user input timezones like this, and
given this is a pretty niche API, it isn't worth prioritizing.