Fix XFormManagementView.get_xform_ids
AttributeError: 'OTPMiddleware' object has no attribute 'process_request'
(cherry picked from commit f7bbbdb8d32a84ef35349c99f4fbc072e0df523b)